"""init_saas_core

Revision ID: de19e92ebfed
Revises: 
Create Date: 2026-02-24 11:01:30.007654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de19e92ebfed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('actor_user_id', sa.BigInteger(), nullable=True),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expert_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('managed_groups',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('p2p_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seller_user_id', sa.BigInteger(), nullable=False),
    sa.Column('token', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('price_currency', sa.String(length=16), nullable=False),
    sa.Column('price_total', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reward_ledger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expert_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['expert_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category_id', name='uq_candidate')
    )
    op.create_table('expert_votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voter_user_id', sa.BigInteger(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['expert_candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voter_user_id', 'candidate_id', name='uq_vote')
    )
    op.drop_index('ix_manh_invoices_user', table_name='manh_invoices', if_exists=True)
    op.drop_table('manh_invoices', if_exists=True)
    op.drop_index('ix_manh_withdrawals_user', table_name='manh_withdrawals')
    op.drop_table('manh_withdrawals')
    op.drop_index('ix_manh_purchases_user', table_name='manh_purchases')
    op.drop_table('manh_purchases')
    op.drop_index('ix_ledger_events_telegram_id', table_name='ledger_events')
    op.drop_table('ledger_events')
    op.drop_table('announcements')
    op.add_column('users', sa.Column('chat_id', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(length=128), nullable=True))
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index('ix_users_email', table_name='users')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'airdrop_claimed')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'email')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'display_name')
    op.drop_column('users', 'marketing_opt_in')
    op.drop_column('users', 'language_code')
    op.drop_column('users', 'balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('balance', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('language_code', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('marketing_opt_in', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('display_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('airdrop_claimed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('users', 'username')
    op.drop_column('users', 'chat_id')
    op.create_table('announcements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_published', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='announcements_pkey')
    )
    op.create_table('ledger_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='ledger_events_pkey')
    )
    op.create_index('ix_ledger_events_telegram_id', 'ledger_events', ['telegram_id'], unique=False)
    op.create_table('manh_purchases',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('manh_amount', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=False),
    sa.Column('ils_amount', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='manh_purchases_pkey'),
    sa.UniqueConstraint('invoice_id', name='uq_manh_purchases_invoice', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_manh_purchases_user', 'manh_purchases', ['user_id', 'created_at'], unique=False)
    op.create_table('manh_withdrawals',
    sa.Column('withdrawal_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('amount_manh', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=False),
    sa.Column('target_ton_address', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), server_default=sa.text("'REQUESTED'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('decided_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('decided_by', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('note', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('withdrawal_id', name='manh_withdrawals_pkey')
    )
    op.create_index('ix_manh_withdrawals_user', 'manh_withdrawals', ['user_id', 'created_at'], unique=False)
    op.create_table('manh_invoices',
    sa.Column('invoice_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ils_amount', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=False),
    sa.Column('manh_amount', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=False),
    sa.Column('ton_amount', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=False),
    sa.Column('ton_ils_rate', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=False),
    sa.Column('ton_treasury_address', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('comment', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('sig16', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('confirmed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('invoice_id', name='manh_invoices_pkey')
    )
    op.create_index('ix_manh_invoices_user', 'manh_invoices', ['user_id', 'created_at'], unique=False)
    op.drop_table('expert_votes')
    op.drop_table('expert_candidates')
    op.drop_table('reward_ledger')
    op.drop_table('p2p_orders')
    op.drop_table('managed_groups')
    op.drop_table('expert_categories')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
